### ISSUE TITLE
how to close one panel when i click on second panel...

### ISSUE THREAD

**Issue by prasann278** [crysfel/Panels#5]
@crysfel
@MatthiasVervaet
@hungdev
there are saveral panel in one view--
i want to close first panel if i click on second one  automaticly please help me out in this....

**Comment by crysfel** [comment]
@prasann278 in the parent component, you will have to keep track of the `expanded` state for all panels that you have. Then simple update the state when the user expands a different panel.

**Comment by prasann278** [comment]
@crysfel 
thanks for your help

**Comment by ShaikhKabeer** [comment]
Hey @prasann278 , any example do you have ?

**Comment by ShaikhKabeer** [comment]
@prasann278 , Please share example if you have

**Comment by ShaikhKabeer** [comment]
@prasann278 , Please share example if you have
